import { createFileRoute } from "@tanstack/react-router";
import { AppLayout } from "@/components/layout/AppLayout";
import { Card, CardTitle } from "@/components/ui/card-basic";
import { FileText, Zap, Activity, Download } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/reports")({
  head: () => ({ meta: [{ title: "Reports · WattWise" }] }),
  component: () => (
    <AppLayout title="Reports">
      <Reports />
    </AppLayout>
  ),
});

const types = [
  {
    id: "consumption",
    title: "Consumption report",
    desc: "kWh usage per meter, summarised by area and day.",
    Icon: Activity,
    files: [
      { name: "Consumption_2025-12.csv", fmt: "CSV" },
      { name: "Consumption_2025-12.pdf", fmt: "PDF" },
    ],
  },
  {
    id: "tamper",
    title: "Tamper report",
    desc: "Illegal connection alerts, dispatches, and resolutions.",
    Icon: Zap,
    files: [
      { name: "Tamper_Q4_2025.pdf", fmt: "PDF" },
    ],
  },
  {
    id: "loadshed",
    title: "Load-shedding impact",
    desc: "Downtime per area and affected consumers.",
    Icon: FileText,
    files: [
      { name: "Loadshed_2025-12.pdf", fmt: "PDF" },
    ],
  },
];

const saved = [
  { name: "Consumption_2025-12.csv", type: "Consumption",   date: "2026-01-03", by: "Thandi Mokoena" },
  { name: "Tamper_Q4_2025.pdf",      type: "Tamper",        date: "2026-01-02", by: "Thandi Mokoena" },
  { name: "Loadshed_2025-12.pdf",    type: "Load-shedding", date: "2025-12-31", by: "System" },
];

function Reports() {
  return (
    <div className="space-y-6">
      <div className="grid md:grid-cols-3 gap-4">
        {types.map((t) => <ReportCard key={t.id} t={t} />)}
      </div>

      <Card>
        <CardTitle hint={`${saved.length} files`}>Saved reports</CardTitle>
        <div className="overflow-x-auto">
          <table className="w-full text-xs min-w-[600px]">
            <thead>
              <tr className="text-left text-[10px] uppercase tracking-wider text-slate-400 border-b border-slate-100">
                <th className="py-2">Name</th>
                <th>Type</th>
                <th>Date</th>
                <th>Generated by</th>
                <th>Download</th>
              </tr>
            </thead>
            <tbody>
              {saved.map((r) => (
                <tr key={r.name} className="border-b border-slate-100 last:border-0">
                  <td className="py-2.5 font-mono">{r.name}</td>
                  <td>{r.type}</td>
                  <td className="text-slate-400">{r.date}</td>
                  <td>{r.by}</td>
                  <td>
                    <button
                      onClick={() => toast.success(`Downloading ${r.name}…`)}
                      className="text-[#005EB8] hover:underline inline-flex items-center gap-1"
                    >
                      <Download className="w-3 h-3" />Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}

function ReportCard({ t }: { t: typeof types[number] }) {
  return (
    <Card>
      <t.Icon className="w-5 h-5 text-[#005EB8] mb-2" />
      <div className="font-semibold text-slate-900">{t.title}</div>
      <div className="text-xs text-slate-400 mt-1 mb-4 leading-relaxed">{t.desc}</div>
      <div className="space-y-2">
        {t.files.map((f) => (
          <button
            key={f.name}
            onClick={() => toast.success(`Downloading ${f.name}…`)}
            className="w-full flex items-center justify-between gap-2 border border-slate-200 rounded-lg px-3 py-2 text-xs text-slate-700 hover:bg-[#EBF5FF] hover:text-[#005EB8] hover:border-[#005EB8]/30 transition-colors group"
          >
            <span className="font-mono truncate">{f.name}</span>
            <span className="flex items-center gap-1 font-semibold flex-shrink-0 text-[#005EB8]">
              <Download className="w-3.5 h-3.5" />{f.fmt}
            </span>
          </button>
        ))}
      </div>
    </Card>
  );
}
