import { createFileRoute } from "@tanstack/react-router";
import { AppLayout } from "@/components/layout/AppLayout";
import { Card, CardTitle } from "@/components/ui/card-basic";
import { useState } from "react";
import { FileText, Zap, Activity, Download, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { format } from "date-fns";

export const Route = createFileRoute("/reports")({
  head: () => ({ meta: [{ title: "Reports · NexMotion" }] }),
  component: () => (
    <AppLayout title="Reports">
      <Reports />
    </AppLayout>
  ),
});

const types = [
  { id: "consumption", title: "Consumption report", desc: "kWh usage per meter, summarised by area and day.", Icon: Activity, formats: ["CSV", "PDF"] },
  { id: "tamper", title: "Tamper report", desc: "Illegal connection alerts, dispatches, and resolutions.", Icon: Zap, formats: ["PDF"] },
  { id: "loadshed", title: "Load-shedding impact", desc: "Downtime per area and affected consumers.", Icon: FileText, formats: ["PDF"] },
];

function Reports() {
  const [saved, setSaved] = useState([
    { name: "Consumption_2025-12.csv", type: "Consumption", date: "2026-01-03", by: "Thandi Mokoena" },
    { name: "Tamper_Q4_2025.pdf", type: "Tamper", date: "2026-01-02", by: "Thandi Mokoena" },
    { name: "Loadshed_2025-12.pdf", type: "Load-shedding", date: "2025-12-31", by: "System" },
  ]);

  return (
    <div className="space-y-6">
      <div className="grid md:grid-cols-3 gap-4">
        {types.map((t) => <ReportCard key={t.id} t={t} onGenerated={(name, type) => setSaved((s) => [{ name, type, date: format(new Date(), "yyyy-MM-dd"), by: "You" }, ...s])} />)}
      </div>

      <Card>
        <CardTitle hint={`${saved.length} files`}>Saved reports</CardTitle>
        <div className="overflow-x-auto">
          <table className="w-full text-xs min-w-[600px]">
            <thead>
              <tr className="text-left text-[10px] uppercase tracking-wider text-muted-foreground border-b border-border">
                <th className="py-2">Name</th><th>Type</th><th>Date</th><th>Generated by</th><th>Download</th>
              </tr>
            </thead>
            <tbody>
              {saved.map((r) => (
                <tr key={r.name} className="border-b border-border last:border-0">
                  <td className="py-2.5 font-mono">{r.name}</td>
                  <td>{r.type}</td>
                  <td className="text-muted-foreground">{r.date}</td>
                  <td>{r.by}</td>
                  <td><button onClick={() => toast.success(`Downloading ${r.name}…`)} className="text-teal-600 hover:underline inline-flex items-center gap-1"><Download className="w-3 h-3"/>Download</button></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}

function ReportCard({ t, onGenerated }: { t: typeof types[number]; onGenerated: (name: string, type: string) => void }) {
  const [from, setFrom] = useState("2026-01-01");
  const [to, setTo] = useState(format(new Date(), "yyyy-MM-dd"));
  const [fmt, setFmt] = useState(t.formats[0]);
  const [busy, setBusy] = useState(false);
  const [ready, setReady] = useState<string | null>(null);

  const gen = () => {
    setBusy(true); setReady(null);
    setTimeout(() => {
      const name = `${t.id}_${from}_to_${to}.${fmt.toLowerCase()}`;
      setBusy(false); setReady(name);
      onGenerated(name, t.title);
      toast.success("Report ready");
    }, 1100);
  };

  return (
    <Card>
      <t.Icon className="w-5 h-5 text-teal-600 mb-2" />
      <div className="font-semibold">{t.title}</div>
      <div className="text-xs text-muted-foreground mt-1 mb-4 leading-relaxed">{t.desc}</div>
      <div className="space-y-2">
        <div className="grid grid-cols-2 gap-2">
          <input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="border border-input rounded-lg px-2 py-1.5 text-xs bg-background" />
          <input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="border border-input rounded-lg px-2 py-1.5 text-xs bg-background" />
        </div>
        <select value={fmt} onChange={(e) => setFmt(e.target.value)} className="w-full border border-input rounded-lg px-2 py-1.5 text-xs bg-background">
          {t.formats.map(f => <option key={f}>{f}</option>)}
        </select>
        <button onClick={gen} disabled={busy} className="w-full bg-teal text-navy font-semibold py-2 rounded-lg text-xs hover:bg-teal-600 disabled:opacity-60 inline-flex items-center justify-center gap-2">
          {busy && <Loader2 className="w-3 h-3 animate-spin" />} {busy ? "Generating…" : "Generate report"}
        </button>
        {ready && <button onClick={() => toast.success("Downloading…")} className="w-full text-xs text-teal-600 hover:underline inline-flex items-center justify-center gap-1"><Download className="w-3 h-3"/>Download {ready}</button>}
      </div>
    </Card>
  );
}
