/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UssdRouteImport } from './routes/ussd'
import { Route as TechnicianRouteImport } from './routes/technician'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MunicipalityRouteImport } from './routes/municipality'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeterMeterIdRouteImport } from './routes/meter.$meterId'

const UssdRoute = UssdRouteImport.update({
  id: '/ussd',
  path: '/ussd',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianRoute = TechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalityRoute = MunicipalityRouteImport.update({
  id: '/municipality',
  path: '/municipality',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeterMeterIdRoute = MeterMeterIdRouteImport.update({
  id: '/meter/$meterId',
  path: '/meter/$meterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/municipality': typeof MunicipalityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/technician': typeof TechnicianRoute
  '/ussd': typeof UssdRoute
  '/meter/$meterId': typeof MeterMeterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/municipality': typeof MunicipalityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/technician': typeof TechnicianRoute
  '/ussd': typeof UssdRoute
  '/meter/$meterId': typeof MeterMeterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/municipality': typeof MunicipalityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/technician': typeof TechnicianRoute
  '/ussd': typeof UssdRoute
  '/meter/$meterId': typeof MeterMeterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/login'
    | '/municipality'
    | '/reports'
    | '/settings'
    | '/technician'
    | '/ussd'
    | '/meter/$meterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/login'
    | '/municipality'
    | '/reports'
    | '/settings'
    | '/technician'
    | '/ussd'
    | '/meter/$meterId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/login'
    | '/municipality'
    | '/reports'
    | '/settings'
    | '/technician'
    | '/ussd'
    | '/meter/$meterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MunicipalityRoute: typeof MunicipalityRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TechnicianRoute: typeof TechnicianRoute
  UssdRoute: typeof UssdRoute
  MeterMeterIdRoute: typeof MeterMeterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ussd': {
      id: '/ussd'
      path: '/ussd'
      fullPath: '/ussd'
      preLoaderRoute: typeof UssdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipality': {
      id: '/municipality'
      path: '/municipality'
      fullPath: '/municipality'
      preLoaderRoute: typeof MunicipalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meter/$meterId': {
      id: '/meter/$meterId'
      path: '/meter/$meterId'
      fullPath: '/meter/$meterId'
      preLoaderRoute: typeof MeterMeterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MunicipalityRoute: MunicipalityRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TechnicianRoute: TechnicianRoute,
  UssdRoute: UssdRoute,
  MeterMeterIdRoute: MeterMeterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
